image: node:10.15.1

pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.4.5
              variables:
                AWS_ACCESS_KEY_ID: "AKIATAIRXHBURAK2QAZ3"
                AWS_SECRET_ACCESS_KEY: "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"
                AWS_DEFAULT_REGION: "us-east-2"
                S3_BUCKET: "ticketwork-frontend"
                ACL: "public-read"
                LOCAL_PATH: "dist"