version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
      - npm install -g jest
  build:
    commands:
      - yarn build
      - npm run test:ci
  post_build:
    commands:
      - echo nothing to do
artifacts:
  files:
    - '**/*'
  base-directory: dist