version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
  post_build:
    commands:
      - npm run serve
artifacts:
  files:
    - '**/*'
  base-directory: dist